name: ci

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      SQLALCHEMY_DATABASE_URI: "postgresql+asyncpg://postgres@127.0.0.1:5432/retry_tasks_lib_test"
      REDIS_URL: redis://127.0.0.1:6379/0
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: retry_tasks_lib_test
      redis:
        image: redis:latest
        ports: 
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: ruff check .
      - run: black --line-length=120 --check .
      - run: xenon .
      - run: mypy olympus_messaging
      - run: pytest --verbose --cov=olympus_messaging --cov-report=term --cov-report=xml --junitxml=report.xml

  release:
    if: github.event_name == 'push'
    name: release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry self add "poetry-dynamic-versioning[plugin]"
      - run: poetry config repositories.pypicloud https://pypi.gb.bink.com/simple
      - run: poetry config http-basic.pypicloud c02bed7a-4224-4fb4-82ad-17499e4d0e4a ${{ secrets.PYPICLOUD_PASSWORD }}
      - run: poetry build
      - run: poetry publish -r pypicloud
